### PR TITLE
Added support for searching for users 

### PR DESCRIPTION
**Pull request by aszaryk**
updated the user search to accept all supported request parameters

### CODE REVIEW

**Comment by tjarrettveracode** [comment]
Reviewing this PR. Noticing that this change replaces the old definition of the method with just an unstructured dictionary -- I wonder if it makes more sense to explicitly add the parameters that are missing rather than relying on the user to read the API spec. There's certainly a pro in that we won't have to update the wrapper if there are further changes, though. Thoughts?

**Comment by aszaryk** [comment]
It seemed there were a few parameters missing in the original definition, and no calling function in api.py existed. For brevity I followed what was done in the Findings API get_findings() function.

**Comment by tjarrettveracode** [comment]
I think what I might do is to go ahead and merge this in, then add another method that offers explicit arguments. It might break one of my existing scripts but that's an easy enough fix. Will investigate making this change to see what the implication might be.

**Comment by tjarrettveracode** [comment]
@aszaryk , I looked at preserving both methods but it doesn't look like Python allows me to do that. I think the right approach here is going to be to add `request_params` as an optional argument alongside the others. I'm going to make some changes to this branch before merge.

**Pull request merged**
